import type {
  Activity,
  BusinessProfile,
  Customer,
  CustomerService,
  Lead,
  OrganizationPreview,
  PortfolioProject,
  ReviewItem,
  ServiceItem,
  SocialChannel,
  User,
} from "@/types";

export const currentUser: User = {
  id: "u1",
  email: "elena@atelierforma.design",
  name: "Elena Vance",
  avatar: "EV",
  role: "admin",
};

export const elanSocialChannels: SocialChannel[] = [
  {
    id: "ig",
    type: "instagram",
    label: "Instagram",
    connected: true,
    handle: "atelierforma.design",
    url: "https://instagram.com/atelierforma.design",
    description: "Visual identity archives, kinetic typography & editorial previews",
    lastSynced: "2026-08-25T10:00:00Z",
  },
  {
    id: "fb",
    type: "facebook",
    label: "Facebook",
    connected: true,
    handle: "atelierforma",
    url: "https://facebook.com/atelierforma",
    description: "Studio news, community releases & design symposiums",
    lastSynced: "2026-08-24T12:00:00Z",
  },
  {
    id: "li",
    type: "linkedin",
    label: "LinkedIn",
    connected: true,
    handle: "atelier-forma",
    url: "https://linkedin.com/company/atelier-forma",
    description: "Design leadership, brand system case studies & client essays",
    lastSynced: "2026-08-23T14:30:00Z",
  },
  {
    id: "tt",
    type: "tiktok",
    label: "TikTok",
    connected: true,
    handle: "atelierforma",
    url: "https://tiktok.com/@atelierforma",
    description: "Behind-the-scenes typesetting, print proofing & studio process",
    lastSynced: "2026-08-25T08:00:00Z",
  },
  {
    id: "x",
    type: "x",
    label: "X (Twitter)",
    connected: true,
    handle: "atelierforma",
    url: "https://x.com/atelierforma",
    description: "Design critiques, type release dispatches & studio notes",
    lastSynced: "2026-08-22T16:00:00Z",
  },
  {
    id: "yt",
    type: "youtube",
    label: "YouTube",
    connected: true,
    handle: "atelierforma",
    url: "https://youtube.com/@atelierforma",
    description: "Case study documentaries, 4K reel breakdowns & masterclasses",
    lastSynced: "2026-08-20T11:00:00Z",
  },
  {
    id: "wa",
    type: "whatsapp",
    label: "WhatsApp",
    connected: true,
    handle: "+234 800 FORMA VIP",
    url: "https://wa.me/2348055966944",
    description: "Direct studio concierge & new project commission desk",
    lastSynced: "2026-08-25T14:00:00Z",
  },
  {
    id: "th",
    type: "threads",
    label: "Threads",
    connected: true,
    handle: "atelierforma.design",
    url: "https://threads.net/@atelierforma.design",
    description: "Design musings, visual essays & typography critiques",
    lastSynced: "2026-08-24T09:00:00Z",
  },
  {
    id: "pi",
    type: "pinterest",
    label: "Pinterest",
    connected: true,
    handle: "atelierforma",
    url: "https://pinterest.com/atelierforma",
    description: "Curated typography specimens, palette studies & print textures",
    lastSynced: "2026-08-21T18:00:00Z",
  },
  {
    id: "web",
    type: "website",
    label: "Website",
    connected: true,
    handle: "atelierforma.design",
    url: "https://atelierforma.design",
    description: "Official digital atelier & client private brief portal",
    lastSynced: "2026-08-25T12:00:00Z",
  },
];

export const elanPortfolio: PortfolioProject[] = [
  {
    id: "proj-1",
    title: "Aethel Luxury Rebrand",
    category: "Brand Identity",
    location: "London & Lagos",
    description:
      "Comprehensive brand identity redesign for a luxury heritage maison including bespoke serif typography, monogram system, foiled stationery suite, and packaging architecture.",
    image:
      "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=1200&q=80",
    order: 0,
    isCover: true,
    gallery: [
      "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "48-Page Brand Book · Custom Monogram · Foil Packaging",
    client: "Aethel Heritage Maison",
    year: "2026",
  },
  {
    id: "proj-2",
    title: "Sora Protocol Design System",
    category: "UI/UX & Product",
    location: "San Francisco, CA",
    description:
      "Next-generation decentralized finance dashboard and mobile app interface, featuring high-contrast dark aesthetics, tokenized component libraries, and kinetic data visualizations.",
    image:
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80",
    order: 1,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "140+ UI Components · iOS & Web · Figma System",
    client: "Sora Decentralized Protocol",
    year: "2026",
  },
  {
    id: "proj-3",
    title: "Kanso Editorial Book No. 04",
    category: "Packaging & Print",
    location: "Tokyo / Milan",
    description:
      "Limited hardcover architectural publication featuring exposed Swiss binding, blind debossed linen cover, custom grid layout systems, and duotone offset printing.",
    image:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
    order: 2,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "320 Pages · Linen Hardcover · Swiss Bound",
    client: "Kanso Architecture Press",
    year: "2025",
  },
  {
    id: "proj-4",
    title: "Vesper Botanical Parfums",
    category: "Packaging & Print",
    location: "Grasse / Paris",
    description:
      "Luxury fragrance packaging design featuring heavy fluted glass label typography, textured paper stock, soft-touch unboxing cartons, and numbered certificates of authenticity.",
    image:
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80",
    order: 3,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "5 Fragrance SKUs · Bespoke Box Architecture · Foiling",
    client: "Maison Vesper",
    year: "2025",
  },
  {
    id: "proj-5",
    title: "Onyx Architectural Monograph",
    category: "Art Direction",
    location: "Stockholm, Sweden",
    description:
      "Complete creative direction and visual identity for a Scandinavian architectural monograph, including spatial photo direction, minimalist poster series, and exhibition signage.",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    order: 4,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "Exhibition Curation · 12 Posters · Monograph",
    client: "Onyx Architecture Studio",
    year: "2025",
  },
  {
    id: "proj-6",
    title: "Hyperion Aerospace Visual System",
    category: "Brand Identity",
    location: "Berlin & Lagos",
    description:
      "Dynamic brand identity and visual language for a sustainable aerospace logistics platform, combining precision technical diagrams, geometric vector marks, and modular guidelines.",
    image:
      "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80",
    order: 5,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "Brand Guideline System · Vector Iconography · Pitch Deck",
    client: "Hyperion Aerospace",
    year: "2026",
  },
  {
    id: "proj-7",
    title: "Lumina Contemporary Art Fair",
    category: "Art Direction",
    location: "Zurich & Basel",
    description:
      "Comprehensive festival visual identity, dynamic kinetic posters, catalog editorial layout, and spatial wayfinding systems for Europe's leading contemporary art symposium.",
    image:
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    order: 6,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1561055657-b9e0bf0fa360?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "Wayfinding Grid · 24 Kinetic Posters · Fair Catalog",
    client: "Lumina Art Foundation",
    year: "2026",
  },
  {
    id: "proj-8",
    title: "Chronos Haute Horlogerie App",
    category: "UI/UX & Product",
    location: "Geneva & London",
    description:
      "Luxury collector companion application with micro-precision haptic feedback, mechanical watch telemetry tracking, and bespoke dark-mode interface architecture.",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    order: 7,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "iOS WatchOS Interface · 85 Micro-Animations · Telemetry",
    client: "Chronos Horlogerie Group",
    year: "2025",
  },
  {
    id: "proj-9",
    title: "Terra Cotta Artisanal Ceramics",
    category: "Packaging & Print",
    location: "Lisbon & Lagos",
    description:
      "Organic terracotta packaging suite featuring blind debossed recycled clay papers, tactile letterpress labels, and minimal photographic visual documentation.",
    image:
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
    order: 8,
    isCover: false,
    gallery: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80",
    ],
    stats: "Recycled Clay Paper Packaging · 8 Tag SKUs · Letterpress",
    client: "Terra Cotta Studio",
    year: "2026",
  },
];

export const elanReviews: ReviewItem[] = [
  {
    id: "rev-1",
    author: "Claire Beaumont",
    role: "Global Marketing Director, Aethel Heritage",
    eventType: "Brand Identity & Monogram System",
    rating: 5,
    comment:
      "Atelier Forma captured our 140-year heritage with absolute elegance while making us feel instantly modern. Their mastery of bespoke typography, print textures, and brand guidelines is unmatched.",
    date: "February 2026",
  },
  {
    id: "rev-2",
    author: "Kenji Sato",
    role: "Founder & CEO, Sora Protocol",
    eventType: "Product UI/UX & Design System",
    rating: 5,
    comment:
      "Working with Elena and her team transformed our product experience. They delivered an elite design system with pixel-perfect tokens that scaled across web and mobile effortlessly.",
    date: "January 2026",
  },
  {
    id: "rev-3",
    author: "Henrietta Berg",
    role: "Senior Partner, Onyx Architecture",
    eventType: "Architectural Monograph & Exhibition",
    rating: 5,
    comment:
      "The editorial monograph and exhibition posters designed by the studio received universal acclaim at Milan Design Week. Subtle, sophisticated, and executed with extreme precision.",
    date: "November 2025",
  },
];

export const businessProfile: BusinessProfile = {
  id: "bp-forma",
  businessName: "Atelier Forma",
  slug: "atelier-forma",
  tagline: "Graphic Design, Brand Architecture & Visual Identity Atelier",
  description:
    "We partner with visionary founders, luxury ateliers, and technology pioneers to craft timeless visual identities, editorial publications, and high-conversion digital experiences.",
  location: "Victoria Island, Lagos & Mayfair, London",
  website: "atelierforma.design",
  email: "studio@atelierforma.design",
  phone: "+234 800 FORMA VIP",
  logoUrl:
    "https://cdn.accessa.ng/test/accessa/louis-dike-ayskyj/images/c95e52aa48bf676ed0d53f36bb957b81.png",
  googleReviewsLink: "https://business.google.com/atelier-forma",
  services: [
    {
      id: "svc-1",
      name: "Brand Identity & Guidelines",
      category: "Identity",
      description:
        "Comprehensive visual identity design including bespoke typography, primary marks, sub-marks, color harmony, and a full brand guidelines bible.",
    },
    {
      id: "svc-2",
      name: "Digital Product & UI/UX Design",
      category: "Digital",
      description:
        "End-to-end design systems, mobile app UI/UX, responsive web interfaces, and interactive prototyping built for scale.",
    },
    {
      id: "svc-3",
      name: "Packaging & Print Architecture",
      category: "Print",
      description:
        "Luxury unboxing experiences, die-cut packaging boxes, embossed foil treatments, and sustainable print production management.",
    },
    {
      id: "svc-4",
      name: "Editorial & Monograph Books",
      category: "Print",
      description:
        "Custom grid layout architecture, multi-lingual typesetting, art monographs, and coffee table publication design.",
    },
    {
      id: "svc-5",
      name: "Motion & Kinetic Typography",
      category: "Digital",
      description:
        "Dynamic 3D logo reveals, typographic animations for social campaigns, billboard digital out-of-home (DOOH) assets, and video title design.",
    },
    {
      id: "svc-6",
      name: "Design Retainer & Creative Direction",
      category: "Retainer",
      description:
        "Dedicated fractional creative director services, monthly design asset sprints, and brand stewardship for growing enterprises.",
    },
  ] as ServiceItem[],
  socialChannels: elanSocialChannels,
  reviews: elanReviews,
  portfolio: elanPortfolio,
  portfolioCategories: ["Brand Identity", "UI/UX & Product", "Packaging & Print", "Art Direction"],
  operatingHours: "Mon–Fri",
  timeFrom: "09:00 AM",
  timeTo: "06:00 PM",
  byAppointmentOnly: false,
  whatsAppNumber: "+234 800 FORMA VIP",
  emailAddress: "studio@atelierforma.design",
  physicalAddress: "14 Victoria Island, Lagos / London W1",
  colors: {
    primary: "#000000",
    secondary: "#0058BE",
    button: "#000000",
    pageBackground: "#faf8f5",
    cardBackground: "#faf6f0",
    text: "#191C1D",
  },
  buttonRadius: "Subtle",
  currency: "NGN",
  showServices: true,
  showPortfolio: true,
  showReviews: true,
  footerEyebrow: "Begin Your Journey",
  footerTitle: "Ready to Create Something Extraordinary?",
  footerDescription:
    "Tell us what you're planning and we'll get back to you to schedule an initial consultation with our creative directors.",
  showFooterCta: true,
  businessType: "service",
  updatedAt: "2026-08-25T12:00:00Z",
};

export const socialChannels: SocialChannel[] = elanSocialChannels;

export const leads: Lead[] = [
  {
    id: "l1",
    name: "Sofia Laurent",
    email: "sofia.laurent@aethel.com",
    phone: "+234 802 555 0142",
    service: "Brand Identity & Guidelines",
    services: ["Brand Identity & Guidelines", "Packaging & Print Architecture"],
    eventDate: "2026-10-18",
    budget: 85000,
    message:
      "We are launching our luxury beauty line and need an end-to-end visual identity and packaging system.",
    status: "new",
    createdAt: "2026-08-24T09:12:00Z",
  },
  {
    id: "l2",
    name: "Julian & Margot",
    email: "julian@soraprotocol.io",
    service: "Digital Product & UI/UX Design",
    services: ["Digital Product & UI/UX Design", "Motion & Kinetic Typography"],
    eventDate: "2027-05-22",
    budget: 120000,
    message:
      "Looking for a design studio to architect our web3 exchange interface and complete token design system.",
    status: "contacted",
    createdAt: "2026-08-23T14:30:00Z",
  },
  {
    id: "l3",
    name: "Nora Chen",
    email: "nora.chen@kansopress.com",
    phone: "+44 20 7946 0958",
    service: "Editorial & Monograph Books",
    services: ["Editorial & Monograph Books"],
    eventDate: "2026-09-04",
    budget: 32000,
    message: "Art direction and 280-page layout design for our upcoming architecture monograph.",
    status: "qualified",
    createdAt: "2026-08-21T11:45:00Z",
  },
  {
    id: "l4",
    name: "Elias & Camille",
    email: "elias@vesperparfums.fr",
    service: "Packaging & Print Architecture",
    services: ["Packaging & Print Architecture"],
    eventDate: "2026-11-12",
    budget: 54000,
    message: "Bespoke perfume bottle typography and unboxing box design for our autumn launch.",
    status: "converted",
    createdAt: "2026-08-19T08:20:00Z",
  },
  {
    id: "l5",
    name: "Atlas Foundation",
    email: "design@atlas.org",
    service: "Design Retainer & Creative Direction",
    services: ["Design Retainer & Creative Direction"],
    eventDate: "2026-12-03",
    budget: 68000,
    message: "Quarterly design retainer for our global foundation reports and digital summits.",
    status: "closed",
    createdAt: "2026-08-16T16:10:00Z",
  },
];

export const customerServices: CustomerService[] = [
  {
    id: "p1",
    customerId: "c1",
    name: "Aethel Brand Architecture",
    service: "Brand Identity & Guidelines",
    amount: 96000,
    status: "active",
    createdAt: "2026-06-02",
  },
  {
    id: "p1-sub1",
    customerId: "c1",
    name: "Foil Packaging & Unboxing Suite",
    service: "Packaging & Print Architecture",
    amount: 18000,
    status: "completed",
    createdAt: "2026-06-15",
    completedAt: "2026-07-20",
  },
  {
    id: "p1-sub2",
    customerId: "c1",
    name: "Kinetic Typography Social Sprints",
    service: "Motion & Kinetic Typography",
    amount: 12000,
    status: "active",
    createdAt: "2026-07-10",
  },
  {
    id: "p2",
    customerId: "c2",
    name: "Kanso Monograph Edition 04",
    service: "Editorial & Monograph Books",
    amount: 28000,
    status: "completed",
    createdAt: "2026-05-12",
    completedAt: "2026-07-18",
  },
  {
    id: "p2-sub1",
    customerId: "c2",
    name: "Milan Exhibition Poster Series",
    service: "Packaging & Print Architecture",
    amount: 15000,
    status: "pending",
    createdAt: "2026-08-10",
  },
  {
    id: "p3",
    customerId: "c3",
    name: "Sora Protocol Design System",
    service: "Digital Product & UI/UX Design",
    amount: 74000,
    status: "pending",
    createdAt: "2026-08-01",
  },
  {
    id: "p3-sub1",
    customerId: "c3",
    name: "Design Token Library & iOS UI Kit",
    service: "Design Retainer & Creative Direction",
    amount: 22000,
    status: "pending",
    createdAt: "2026-08-15",
  },
];

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Aethel Heritage Maison",
    email: "claire@aethel.com",
    phone: "+234 803 555 0177",
    company: "Aethel Group",
    services: [customerServices[0], customerServices[1], customerServices[2]],
    totalRevenue: 126000,
    notes:
      "Requires classic serif typography, minimal foil stamping, and warm editorial paper stock.",
    isActive: true,
    createdAt: "2026-06-01",
  },
  {
    id: "c2",
    name: "Kanso Architecture Press",
    email: "press@kanso.jp",
    phone: "+234 809 794 6095",
    company: "Kanso Press",
    services: [customerServices[3], customerServices[4]],
    totalRevenue: 43000,
    notes:
      "Japanese minimalist architectural publications. Emphasizes negative space and Swiss typography.",
    isActive: true,
    createdAt: "2026-05-10",
  },
  {
    id: "c3",
    name: "Sora Protocol Labs",
    email: "kenji@soraprotocol.io",
    company: "Sora Labs",
    services: [customerServices[5], customerServices[6]],
    totalRevenue: 96000,
    notes:
      "Web3 fintech platform. Requires dark-mode first design tokens, high contrast, and smooth micro-interactions.",
    isActive: true,
    createdAt: "2026-08-01",
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    customerId: "c1",
    type: "service",
    description: "Brand guidelines bible and typography tokens approved",
    timestamp: "2026-08-25T13:00:00Z",
  },
  {
    id: "a2",
    customerId: "c1",
    type: "note",
    description: "Added unboxing box dielines and foil stamp proofs",
    timestamp: "2026-08-24T10:30:00Z",
  },
  {
    id: "a3",
    customerId: "c1",
    type: "contact",
    description: "Sent consultation update for Q4 marketing collateral",
    timestamp: "2026-08-22T15:15:00Z",
  },
];

export const featuredOrganizations: OrganizationPreview[] = [
  {
    id: "org-1",
    name: "Atelier Forma",
    slug: "atelier-forma",
    eyebrow: "Graphic Design & Brand Atelier · Lagos / London",
    tagline: "We design timeless visual identities, editorial books, and digital systems.",
    logoUrl:
      "https://cdn.accessa.ng/test/accessa/louis-dike-ayskyj/images/c95e52aa48bf676ed0d53f36bb957b81.png",
    badge: "Bespoke Design",
  },
  {
    id: "org-2",
    name: "Maison Bell Events",
    slug: "maison-bell-events",
    eyebrow: "Haute Couture & Bridal · Paris / London",
    tagline: "Editorial wedding design and high-society galas across Europe's finest landmarks.",
    logoUrl: "https://cdn.logosystem.co/logos/the-huntington.webp",
    badge: "Haute Couture",
  },
  {
    id: "org-3",
    name: "Lumio Atelier",
    slug: "lumio-atelier",
    eyebrow: "Spatial Design & Light · Milan",
    tagline: "Architectural lighting, experiential banquets, and modern spatial art for galas.",
    logoUrl: "https://cdn.logosystem.co/logos/hatil.webp",
    badge: "Architectural Design",
  },
  {
    id: "org-4",
    name: "Meridian Celebrations",
    slug: "meridian-celebrations",
    eyebrow: "Destination Galas · Lake Como / Amalfi",
    tagline:
      "Multi-day lakeside celebrations and private yacht receptions for discerning clientele.",
    logoUrl: "https://cdn.logosystem.co/logos/mila.webp",
    badge: "Destination Estate",
  },
  {
    id: "org-5",
    name: "Arcwell Bespoke",
    slug: "arcwell-bespoke",
    eyebrow: "Private Estate Soirées · New York",
    tagline:
      "Discreet milestone celebrations, black-tie dinners, and bespoke artistic productions.",
    logoUrl: "https://cdn.logosystem.co/logos/fourthfloor.webp",
    badge: "White-Glove Concierge",
  },
  {
    id: "org-6",
    name: "Solace Studios",
    slug: "solace-studios",
    eyebrow: "Ultra-Luxury Gala Productions · Dubai",
    tagline: "Iconic corporate galas and royal wedding productions curated with quiet elegance.",
    logoUrl: "https://cdn.logosystem.co/logos/renforce.webp",
    badge: "Grand Productions",
  },
  {
    id: "org-7",
    name: "Nova Labs Atelier",
    slug: "nova-labs-atelier",
    eyebrow: "Sensory Scenography · Tokyo / Kyoto",
    tagline: "Immersive multi-sensory pavilions and avant-garde gala installations.",
    logoUrl: "https://cdn.logosystem.co/logos/the-huntington.webp",
    badge: "Avant-Garde",
  },
  {
    id: "org-8",
    name: "Monolith Events",
    slug: "monolith-events",
    eyebrow: "Architectural Banquets · Stockholm",
    tagline: "Monolithic tablescapes, raw stone accents, and Scandinavian culinary theater.",
    logoUrl: "https://cdn.logosystem.co/logos/hatil.webp",
    badge: "Minimalist Studio",
  },
  {
    id: "org-9",
    name: "Haven Gala Design",
    slug: "haven-gala-design",
    eyebrow: "Private Island Soirées · Caribbean",
    tagline: "Ultra-private destination retreats and coastal candlelit beachside celebrations.",
    logoUrl: "https://cdn.logosystem.co/logos/mila.webp",
    badge: "Island Retreat",
  },
  {
    id: "org-10",
    name: "Apex Atelier",
    slug: "apex-atelier",
    eyebrow: "High-Society Summits · London",
    tagline: "Prestigious corporate keynote galas and private member club productions.",
    logoUrl: "https://cdn.logosystem.co/logos/fourthfloor.webp",
    badge: "Private Members",
  },
  {
    id: "org-11",
    name: "Atlas Creative",
    slug: "atlas-creative",
    eyebrow: "Editorial Floral Design · Copenhagen",
    tagline: "Wild botanicals, sculptural centerpieces, and organic couture styling.",
    logoUrl: "https://cdn.logosystem.co/logos/renforce.webp",
    badge: "Floral Scenography",
  },
  {
    id: "org-12",
    name: "Vanta Spatial Arts",
    slug: "vanta-spatial-arts",
    eyebrow: "Experiential Galas · Berlin",
    tagline: "Dark-mode architectural lighting and contemporary experiential dining events.",
    logoUrl:
      "https://cdn.accessa.ng/test/accessa/louis-dike-ayskyj/images/c95e52aa48bf676ed0d53f36bb957b81.png",
    badge: "Experiential Arts",
  },
];
